name: 'lark(fieshu)-notify-action'
description: 'This action will send a notification to lark'
author: 'maximus'
branding:
  color: 'green'
  icon: 'award'

# Define your inputs here.
inputs:
  hookToken:
    description: 'webhook access token'
    required: true
  secret:
    description: 'webhook secret'
    required: false
  status:
    description: 'status'
    default: 'success'
    required: true
  platform:
    description: 'msg type, default:lark. feishu/lark'
    required: true
    default: 'lark'
  title:
    description: 'title'
    required: true
    default: '项目部署通知'
  titleColor:
    description: 'titleColor'
    required: false
  message:
    description: 'message'
  buttonLink:
    description: 'buttonLink'

runs:
  using: node20
  main: dist/index.js
