name: Lark Notification

on: 
  pull_request:
  issues:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print job status for debugging
        run: echo ${{ job.status }}

      - name: Lark Notification
        uses: maximus-1024/lark-notify-action@v1.0.0
        with:
          hookToken: ${{ secrets.LARK_HOOK }}
          status: ${{ job.status }}
