name: Lark Notification

on: 
  pull_request:
  issues:
  push:

jobs:
  gasssss:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lark Notification
        uses: adrian-susanto/lark-notify-action@main
        with:
          title: ${{ github.repository }}
          hookToken: ${{ secrets.LARK_HOOK }}
          status: ${{ job.status }}
