name: Lark Notification

on: 
  pull_request:
  issues:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if LARK_HOOK secret is available
        run: |
          if [ -z "${{ secrets.LARK_HOOK }}" ]; then
            echo "LARK_HOOK is not set"
          else
            echo "LARK_HOOK is set"
          fi

      - name: Lark Notification
        uses: maximus-1024/lark-notify-action@v1.0.0
        with:
          hookToken: ${{ secrets.LARK_HOOK }}
          status: ${{ job.status }}
