name: Lark Notification

on: 
  pull_request:
  issues:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Lark Hook Secret
        run: echo ${{ secrets.LARK_HOOK }}

      - name: Lark Notification
        uses: maximus-1024/lark-notify-action@v1.0.0
        with:
          hookToken: ${{ secrets.LARK_HOOK }}
          status: ${{ job.status }}
